### ISSUE TITLE
Errors during install from source

### ISSUE THREAD

**Issue by menggerSherry** [deepmodeling/deepmd-kit#1746]
### Summary

I try to install from the source following [https://github.com/deepmodeling/deepmd-kit/blob/master/doc/install/install-from-source.md](this). But I got errors when I try to install python interface.

Details are:
```
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Obtaining file:///storage/mxy/MD/deepmd-kit2
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: typing-extensions in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from deepmd-kit==2.1.1) (3.7.4.3)
Requirement already satisfied: packaging in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from deepmd-kit==2.1.1) (21.3)
Requirement already satisfied: importlib-metadata>=1.4 in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from deepmd-kit==2.1.1) (4.8.3)
Requirement already satisfied: wcmatch in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from deepmd-kit==2.1.1) (8.3)
Requirement already satisfied: h5py in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from deepmd-kit==2.1.1) (3.1.0)
Requirement already satisfied: numpy in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from deepmd-kit==2.1.1) (1.19.5)
Requirement already satisfied: dargs>=0.2.6 in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from deepmd-kit==2.1.1) (0.2.9)
Requirement already satisfied: pyyaml in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from deepmd-kit==2.1.1) (6.0)
Requirement already satisfied: scipy in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from deepmd-kit==2.1.1) (1.5.4)
Requirement already satisfied: python-hostlist>=1.21 in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from deepmd-kit==2.1.1) (1.21)
Requirement already satisfied: zipp>=0.5 in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from importlib-metadata>=1.4->deepmd-kit==2.1.1) (3.6.0)
Requirement already satisfied: cached-property in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from h5py->deepmd-kit==2.1.1) (1.5.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from packaging->deepmd-kit==2.1.1) (3.0.9)
Requirement already satisfied: bracex>=2.1.1 in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages (from wcmatch->deepmd-kit==2.1.1) (2.2.1)
Installing collected packages: deepmd-kit
  Running setup.py develop for deepmd-kit
    ERROR: Command errored out with exit status 1:
     command: /storage/mxy/MD/deepmd-kit/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/storage/mxy/MD/deepmd-kit2/setup.py'"'"'; __file__='"'"'/storage/mxy/MD/deepmd-kit2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /storage/mxy/MD/deepmd-kit2/
    Complete output (206 lines):
    Not searching for unused variables given on the command line.
    -- The C compiler identification is GNU 7.5.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- The CXX compiler identification is GNU 7.5.0
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /storage/mxy/MD/deepmd-kit2/_cmake_test_compile/build
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/cc - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found Git: /usr/bin/git (found version "2.17.1")
    -- Supported model version: 1.1
    -- Will not build nv GPU support
    -- Will not build AMD GPU support
    -- Disabled cpp interface build, looking for tensorflow_framework
    -- Found TensorFlow: /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/include, , /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/libtensorflow_framework.so.2  in /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow;/storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/../tensorflow_core;/storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow;/storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/../tensorflow_core;/usr/;/usr/local/ (found version "2.5.0")
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Automatically determined OP_CXX_ABI=0
    -- Set GLIBCXX_USE_CXX_ABI=0 when compiling ops
    -- Found OpenMP_C: -fopenmp (found version "4.5")
    -- Found OpenMP_CXX: -fopenmp (found version "4.5")
    -- Found OpenMP: TRUE (found version "4.5")
    -- /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/libtensorflow_framework.so.2
    -- Configuring done
    -- Generating done
    CMake Warning:
      Manually-specified variables were not used by the project:
    
        PYTHON_INCLUDE_DIR
        PYTHON_LIBRARY
        PYTHON_VERSION_STRING
        Python3_EXECUTABLE
        Python3_INCLUDE_DIR
        Python3_LIBRARY
        Python_EXECUTABLE
        Python_INCLUDE_DIR
        Python_LIBRARY
        SKBUILD
    
    
    -- Build files have been written to: /storage/mxy/MD/deepmd-kit2/_skbuild/linux-x86_64-3.6/cmake-build
    [1/56] Building CXX object op/CMakeFiles/op_abi.dir/custom_op.cc.o
    [2/56] Building CXX object op/CMakeFiles/op_abi.dir/map_aparam.cc.o
    [3/56] Building CXX object op/CMakeFiles/op_abi.dir/gelu_multi_device.cc.o
    [4/56] Building CXX object op/CMakeFiles/op_abi.dir/prod_force.cc.o
    [5/56] Building CXX object op/CMakeFiles/op_abi.dir/soft_min.cc.o
    [6/56] Building CXX object op/CMakeFiles/op_abi.dir/prod_env_mat_multi_device.cc.o
    [7/56] Building CXX object op/CMakeFiles/op_abi.dir/soft_min_virial.cc.o
    [8/56] Building CXX object op/CMakeFiles/op_abi.dir/__/lib/src/SimulationRegion.cpp.o
    [9/56] Building CXX object op/CMakeFiles/op_abi.dir/ewald_recp.cc.o
    [10/56] Building CXX object op/CMakeFiles/op_abi.dir/pair_tab.cc.o
    [11/56] Building CXX object op/CMakeFiles/op_abi.dir/neighbor_stat.cc.o
    [12/56] Building CXX object op/CMakeFiles/op_abi.dir/descrpt_se_a_ef.cc.o
    [13/56] Building CXX object op/CMakeFiles/op_abi.dir/descrpt_se_a_ef_para.cc.o
    [14/56] Building CXX object op/CMakeFiles/op_abi.dir/soft_min_force.cc.o
    [15/56] Building CXX object op/CMakeFiles/op_abi.dir/prod_virial.cc.o
    [16/56] Building CXX object op/CMakeFiles/op_abi.dir/prod_force_multi_device.cc.o
    [17/56] Building CXX object op/CMakeFiles/op_abi.dir/__/lib/src/neighbor_list.cc.o
    [18/56] Building CXX object op/CMakeFiles/op_abi.dir/prod_virial_multi_device.cc.o
    [19/56] Building CXX object op/CMakeFiles/op_abi.dir/descrpt_se_a_ef_vert.cc.o
    [20/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/coord.cc.o
    [21/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/map_aparam.cc.o
    [22/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/gelu.cc.o
    [23/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/SimulationRegion.cpp.o
    [24/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/env_mat.cc.o
    [25/56] Building CXX object op/CMakeFiles/op_abi.dir/descrpt.cc.o
    [26/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/fmt_nlist.cc.o
    [27/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/ewald.cc.o
    [28/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/pair_tab.cc.o
    [29/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/prod_force.cc.o
    [30/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/prod_force_grad.cc.o
    [31/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/prod_virial.cc.o
    [32/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/region.cc.o
    [33/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/prod_virial_grad.cc.o
    [34/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/prod_env_mat.cc.o
    [35/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/soft_min_switch.cc.o
    [36/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/soft_min_switch_virial_grad.cc.o
    [37/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/soft_min_switch_force.cc.o
    [38/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/soft_min_switch_force_grad.cc.o
    [39/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/soft_min_switch_virial.cc.o
    [40/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/utilities.cc.o
    [41/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/neighbor_list.cc.o
    [42/56] Building CXX object lib/CMakeFiles/deepmd.dir/src/tabulate.cc.o
    [43/56] Linking CXX shared library lib/libdeepmd.so
    [44/56] Building CXX object op/CMakeFiles/op_abi.dir/tabulate_multi_device.cc.o
    [45/56] Building CXX object op/CMakeFiles/op_grads.dir/custom_op.cc.o
    [46/56] Building CXX object op/CMakeFiles/op_abi.dir/unaggregated_grad.cc.o
    [47/56] Building CXX object op/CMakeFiles/op_grads.dir/soft_min_force_grad.cc.o
    [48/56] Building CXX object op/CMakeFiles/op_grads.dir/prod_force_grad.cc.o
    [49/56] Building CXX object op/CMakeFiles/op_abi.dir/optimizer/parallel.cc.o
    FAILED: op/CMakeFiles/op_abi.dir/optimizer/parallel.cc.o
    /usr/bin/c++ -Dop_abi_EXPORTS -I/storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/include -I/storage/mxy/MD/deepmd-kit2/source/lib/include -fopenmp -O3 -DNDEBUG -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -std=gnu++11 -MD -MT op/CMakeFiles/op_abi.dir/optimizer/parallel.cc.o -MF op/CMakeFiles/op_abi.dir/optimizer/parallel.cc.o.d -o op/CMakeFiles/op_abi.dir/optimizer/parallel.cc.o -c /storage/mxy/MD/deepmd-kit2/source/op/optimizer/parallel.cc
    In file included from /storage/mxy/MD/deepmd-kit2/source/op/optimizer/parallel.cc:10:0:
    /storage/mxy/MD/deepmd-kit2/source/op/optimizer/parallel.cc: In lambda function:
    /storage/mxy/MD/deepmd-kit2/source/op/optimizer/parallel.cc:150:29: error: invalid new-expression of abstract class type ‘DPParallel’
     REGISTER_GRAPH_OPTIMIZER_AS(DPParallel, "dpparallel");
                                 ^
    /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.h:72:29: note: in definition of macro ‘REGISTER_GRAPH_OPTIMIZER_AS’
               []() { return new MyCustomGraphOptimizerClass; }, (name));   \
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /storage/mxy/MD/deepmd-kit2/source/op/optimizer/parallel.cc:5:0:
    /storage/mxy/MD/deepmd-kit2/source/op/optimizer/parallel.h:9:7: note:   because the following virtual functions are pure within ‘DPParallel’:
     class DPParallel : public CustomGraphOptimizer {
           ^~~~~~~~~~
    In file included from /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/grappler/optimizers/custom_graph_optimizer.h:19:0,
                     from /storage/mxy/MD/deepmd-kit2/source/op/optimizer/parallel.h:4,
                     from /storage/mxy/MD/deepmd-kit2/source/op/optimizer/parallel.cc:5:
    /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/grappler/optimizers/graph_optimizer.h:70:16: note:        virtual void tensorflow::grappler::GraphOptimizer::Feedback(tensorflow::grappler::Cluster*, const tensorflow::grappler::GrapplerItem&, const tensorflow::GraphDef&, double)
       virtual void Feedback(Cluster* cluster, const GrapplerItem& item,
                    ^~~~~~~~
    In file included from /storage/mxy/MD/deepmd-kit2/source/op/optimizer/parallel.cc:10:0:
    /storage/mxy/MD/deepmd-kit2/source/op/optimizer/parallel.cc: At global scope:
    /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.h:72:67: error: no matching function for call to ‘tensorflow::grappler::CustomGraphOptimizerRegistrar::CustomGraphOptimizerRegistrar({anonymous}::<lambda()>, const char [11])’
               []() { return new MyCustomGraphOptimizerClass; }, (name));   \
                                                                       ^
    /storage/mxy/MD/deepmd-kit2/source/op/optimizer/parallel.cc:150:1: note: in expansion of macro ‘REGISTER_GRAPH_OPTIMIZER_AS’
     REGISTER_GRAPH_OPTIMIZER_AS(DPParallel, "dpparallel");
     ^
    /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.h:61:12: note: candidate: tensorflow::grappler::CustomGraphOptimizerRegistrar::CustomGraphOptimizerRegistrar(const Creator&, const string&)
       explicit CustomGraphOptimizerRegistrar(
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.h:61:12: note:   no known conversion for argument 1 from ‘{anonymous}::<lambda()>’ to ‘const Creator& {aka const std::function<tensorflow::grappler::CustomGraphOptimizer*()>&}’
    /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.h:59:7: note: candidate: constexpr tensorflow::grappler::CustomGraphOptimizerRegistrar::CustomGraphOptimizerRegistrar(const tensorflow::grappler::CustomGraphOptimizerRegistrar&)
     class CustomGraphOptimizerRegistrar {
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.h:59:7: note:   candidate expects 1 argument, 2 provided
    /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.h:59:7: note: candidate: constexpr tensorflow::grappler::CustomGraphOptimizerRegistrar::CustomGraphOptimizerRegistrar(tensorflow::grappler::CustomGraphOptimizerRegistrar&&)
    /storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.h:59:7: note:   candidate expects 1 argument, 2 provided
    [50/56] Building CXX object op/CMakeFiles/op_grads.dir/prod_virial_grad.cc.o
    [51/56] Building CXX object op/CMakeFiles/op_grads.dir/prod_force_grad_multi_device.cc.o
    [52/56] Building CXX object op/CMakeFiles/op_grads.dir/soft_min_virial_grad.cc.o
    [53/56] Building CXX object op/CMakeFiles/op_grads.dir/prod_virial_grad_multi_device.cc.o
    ninja: build stopped: subcommand failed.
    /tmp/pip-build-env-6lj6gnj7/overlay/lib/python3.6/site-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
      File "/tmp/pip-build-env-6lj6gnj7/overlay/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
        cmkr.make(make_args, install_target=cmake_install_target, env=env)
      File "/tmp/pip-build-env-6lj6gnj7/overlay/lib/python3.6/site-packages/skbuild/cmaker.py", line 680, in make
        self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
      File "/tmp/pip-build-env-6lj6gnj7/overlay/lib/python3.6/site-packages/skbuild/cmaker.py", line 719, in make_impl
        os.path.abspath(CMAKE_BUILD_DIR()),
    An error occurred while building with CMake.
      Command:
        cmake --build . --target install --config Release --
      Install target:
        install
      Source directory:
        /storage/mxy/MD/deepmd-kit2
      Working directory:
        /storage/mxy/MD/deepmd-kit2/_skbuild/linux-x86_64-3.6/cmake-build
    Please check the install target is valid and see CMake's output for more information.
    
    
    --------------------------------------------------------------------------------
    -- Trying "Ninja" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Ninja" generator - success
    --------------------------------------------------------------------------------
    
    Configuring Project
      Working directory:
        /storage/mxy/MD/deepmd-kit2/_skbuild/linux-x86_64-3.6/cmake-build
      Command:
        cmake /storage/mxy/MD/deepmd-kit2/source -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/storage/mxy/MD/deepmd-kit2/_skbuild/linux-x86_64-3.6/cmake-install -DPYTHON_VERSION_STRING:STRING=3.6.9 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-6lj6gnj7/overlay/lib/python3.6/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/storage/mxy/MD/deepmd-kit/env/bin/python -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPython3_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPython_EXECUTABLE:FILEPATH=/storage/mxy/MD/deepmd-kit/env/bin/python -DPython_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPython_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPYTHON_EXECUTABLE:FILEPATH=/storage/mxy/MD/deepmd-kit/env/bin/python -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.6m -DPYTHON_LIBRARY:PATH=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DCMAKE_MAKE_PROGRAM:FILEPATH=/tmp/pip-build-env-6lj6gnj7/overlay/lib/python3.6/site-packages/ninja/data/bin/ninja -DTENSORFLOW_ROOT:STRING=/storage/mxy/MD/deepmd-kit/env/lib/python3.6/site-packages/tensorflow -DBUILD_PY_IF:BOOL=TRUE -DBUILD_CPP_IF:BOOL=FALSE -DCMAKE_BUILD_TYPE:STRING=Release
    
    Traceback (most recent call last):
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /storage/mxy/MD/deepmd-kit/env/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/storage/mxy/MD/deepmd-kit2/setup.py'"'"'; __file__='"'"'/storage/mxy/MD/deepmd-kit2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available.
You should consider upgrading via the '/storage/mxy/MD/deepmd-kit/env/bin/python -m pip install --upgrade pip' command.
```

**Comment by njzjz** [comment]
Already fixed by #1697.

**Comment by ipe-zhangyz** [comment]
I still encounter with this error when building from v2.1.3，which has already have #1697 merged. But I can finish the building with v2.1.0 in the same environment.

**Comment by ipe-zhangyz** [comment]
I'm using TF 1.15. The patch of source/op/optimizer/parallel.h only has effect on TF 2.0~2.5. I expanded the range to TF 1.x and the compilation error disappeared. Not sure if it's a proper solution😂

**Comment by ipe-zhangyz** [comment]
> 

Only modified the line `#if TF_MAJOR_VERSION >= 2 && TF_MINOR_VERSION < 6` of _source/op/optimizer/parallel.h_ to `#if (TF_MAJOR_VERSION >= 2 && TF_MINOR_VERSION < 6) || TF_MAJOR_VERSION < 2`
